services:
  sqlserver:
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Password123@!}
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "${MSSQL_PORT:-2433}:1433"

  users.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Password123@!}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 3s
    ports:
      - "${USERS_API_PORT:-5020}:8080"

  web:
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:4000/health" ]
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 3s
    ports:
      - "80:4000"
      - "4200:4000"
