name: dockertutorial

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #user: root
    #command: bash -c "apt-get update && apt-get install -y mssql-tools unixodbc-dev && echo \"export PATH=\\\"\\$PATH:/opt/mssql-tools/bin\\\"\" >> ~/.bashrc && exec /opt/mssql/bin/sqlservr"
    volumes:
      - sqlserver.data:/var/opt/mssql

  users.api:
    image: dockertutorial/users/api:${TAG:-prod}
    build:
      context: .
      dockerfile: src/api/Users.API/Dockerfile
    #depends_on:
      #sqlserver:
        #condition: service_healthy

  web:
    image: dockertutorial/web:${TAG:-prod}
    build:
      context: .
      dockerfile: src/web/Dockerfile

volumes:
  sqlserver.data:
