name: dockertutorial

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlserver.data:/var/opt/mssql

  users.api:
    image: dockertutorial/users/api:${TAG:-dev}
    build:
      context: .
      dockerfile: src/api/Users.API/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy

  web:
    image: dockertutorial/web:${TAG:-dev}
    build:
      context: .
      dockerfile: src/web/Dockerfile

volumes:
  sqlserver.data:
